name: My go workflow
on: pull_request

jobs:
  my-go-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: arnested/go-version-action@v1
        id: go-version

      - name: Install Go ${{ steps.go-version.outputs.minimal }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.minimal }}
          check-latest: true

      - name: go test
        run: go test -v -race -cover -covermode=atomic -coverprofile=coverage.txt ./...
